### ISSUE TITLE
French version of the article

### ISSUE THREAD

**Issue by gtedavid** [awsdocs/amazon-pinpoint-user-guide#11]
This is a proposition of a translation of this article https://docs.aws.amazon.com/pinpoint/latest/userguide/channels-email-setup-production-access.html, following this pop-up message 
![image](https://user-images.githubusercontent.com/60758334/200179547-6946ad64-e2a5-4bab-be55-e44b36d2b5b2.png)

I'm not an expert, and I don't know if I'm doing this the right way or if this is the right place to do it at all.

```
Nous utilisons un environnement isolé de test, bac à sable, pour aider à protéger nos consommateurs d'abus et de fraudes. L'environnement de bac à sable vous aide à permettre d'évaluer la réputation de l'envoyeur avec le FAI (Fournisseur d'Accès Internet) et les adresses mails des destinataires. Le nouveau email utilisateur Amazon Pinpoint comptes sont placés dans un environnement de bac à sable. Pendant que votre compte est dans le bac à sable, vous avez accès à toutes les méthodes d'envoi d'email de Amazon Pinpoint, avec les restrictions suivantes :

- Vous pouvez envoyer d'une adresse mail vérifiée et de domaines vérifiés.
- Vous pouvez envoyer des emails aux adresses mails que vous seuls avez vérifiée(s) ou aux adresses mails associées à l'adresse mail du simulateur.
- Vous pouvez envoyer un maximum de 200 messages dans les 24 heures.
- Vous pouvez envoyer un maximum d'un message par secondes.

Pour en apprendre plus sur les restrictions, voir [Requesting a quota increase](https://docs.aws.amazon.com/pinpoint/latest/userguide/channels-email-manage-limits.html#channels-email-manage-limits-increase-case).
```

Please note that despite my French, there may be errors in the text, like for example : 
``` que vous seuls avez vérifiée(s) ``` I have a doubt on the é - e - s according due to the subject and "COD" and stuff

Once more I'm not sure this is the place to post this and there is somewhat some ambiguities in the text ``` only to addresses that you have verified or addresses that are associated with the mailbox simulator``` is the mailbox simulator independent or linked to the original mailbox or is it only linked to the sandbox simulator.....

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
