### ISSUE TITLE
Misleading in this documentation

### ISSUE THREAD

**Issue by mengyangbai** [awsdocs/amazon-pinpoint-user-guide#7]
https://github.com/awsdocs/amazon-pinpoint-user-guide/blob/master/doc-source/channels-sms-awssupport-long-code.md

Requesting a long code outside of the U.S. and Canada 
If you're located outside of the United States or Canada, you need to create a ticket in the AWS Support Center requesting any long codes. 

It should be like
If your long code of the United States or Canada, you need to create a ticket in the AWS Support Center requesting SMS.

1, Confirmed from console, you can request the code outside US and Canada, but is with SMS disabled.
2, Reading the whole messages, if no use case cover for long code is not in Canada&US, while the company location is in Canada&US

Please double check and confirm, and clarify this part, thanks.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
